language: node_js

node_js:
  - 12

before_script:
  - npm run tsc

script:
  - npm run test:cov
  - npm install codecov -g

after_success:
  - codecov

notifications:
  email:
    - udi.talias@gmail.com
